;START_OF_HEADER
;HEADER_VERSION:0.1
;FLAVOR:Griffin
;GENERATOR.NAME:Cura_SteamEngine
;GENERATOR.VERSION:5.6.0
;GENERATOR.BUILD_DATE:2023-11-28
;TARGET_MACHINE.NAME:Ultimaker S5

;EXTRUDER_TRAIN.0.INITIAL_TEMPERATURE:<TOOLTEMP>
;EXTRUDER_TRAIN.0.MATERIAL.VOLUME_USED:0
;EXTRUDER_TRAIN.0.MATERIAL.GUID::506c9f0d-e3aa-4bd4-b2d2-23e2425b1aa9
;EXTRUDER_TRAIN.0.NOZZLE.DIAMETER:<NOZZLE_DIAMETER>

-- Build plate management
;BUILD_PLATE.TYPE:glass
;BUILD_PLATE.INITIAL_TEMPERATURE:<HBPTEMP>

-- Printing time estimation
;PRINT.TIME:0

-- End of the header
;END_OF_HEADER